plot_path: ./data/plot.tok.gt9.5000
quote_path: ./data/quote.tok.gt9.5000
train_size: 0.9
vocab_max_doc_freq: 0.9
vocab_min_count: 5

word2vec_model_path: ./models/word2vec.pth
train_new_word2vec_model: False
word2vec_lr: 0.001
radius: 4
negative_samples_n: 32
word2vec_epoch_n: 200
word2vec_batch_size: 48
word2vec_early_stopping_patience: 10
word2vec_max_batches_per_epoch_train: 3000

cnn_model_name: cnn_sentence_cl
cnn_model_dir: ./models_cnn
train_new_cnn_model: True
window_size: 4
features_num: 200
max_sentence_len: 30
device: cpu
cnn_lr: 0.03
cnn_epoch_n: 100
cnn_batch_size: 48
cnn_early_stopping_patience: 20
cnn_max_batches_per_epoch_train: 4000
cnn_optimizer: adam

